// <auto-generated />
namespace ECommerce.DL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _05102017partII : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_05102017partII));
        
        string IMigrationMetadata.Id
        {
            get { return "201710050635228_05102017partII"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
